### ISSUE TITLE
Hibernate4Module causes Type Erasure 

### ISSUE THREAD

**Issue by agorina** [FasterXML/jackson-datatype-hibernate#81] opened 2015-12-28 02:41 UTC
I have an object that contains the following object that in turn has a collection of polymorphic objects. 
```
public class RecordFilters implements RecordFilter {
    @XmlElementRef
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
    @JsonSubTypes({ @JsonSubTypes.Type(value = EmptyRecordFilter.class),
                    @JsonSubTypes.Type(value = RangeRecordFilter.class) })
    private List<AbstractRecordFilter> filters;
...
```

Without registering Hibernate4Module, I am able to serialize/deserialize the parent object with all its children. 

Calling registerModule with Hibernate4Module causes the failure. 
```
final ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new Hibernate4Module());
```
When I examine the difference, I can see that with Hibernate4Module being registered, the serialized object is missing @type for objects within RecordFilter.

**Comment by cowtowncoder** [comment] 2015-12-28 04:11
I would need a reproduction of this (ideally unit test); above is not enough to trigger the issue.

**Comment by agorina** [comment] 2015-12-28 20:41
Let me know if this is enough:
```
public interface RecordFilter {
}
```
```
public abstract class AbstractRecordFilter implements RecordFilter {
}
```
```
@XmlRootElement(name="emptyRecordFilter")
@XmlAccessorType(XmlAccessType.FIELD)
@JsonTypeName(value="emptyRecordFilter")
public class EmptyRecordFilter extends AbstractRecordFilter {
    private Expression expr;

    EmptyRecordFilter() {
    }

    public EmptyRecordFilter(Expression expr) {
        this.expr = expr;
    }
}
```

```
public class Expression {
    @XmlValue
    private String expression;

    Expression() {
    }

    public Expression(String expression) {
        this.expression = expression;
    }

    public String getExpression() {
        return expression;
    }

    public static Expression simpleFieldExpression(String field) {
        return new Expression("${" + field + "}");
    }
}
```
```
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public abstract class BaseLayout {
    private RecordFilters recordFilters;

    public RecordFilters getRecordFilters() {
        return recordFilters;
    }

    public BaseLayout addRecordFilter(AbstractRecordFilter recordFilter) {
        if (recordFilters == null) {
            recordFilters = new RecordFilters();
        }
        recordFilters.add(recordFilter);
        return this;
    }
}
```
```
@XmlRootElement(name="testLayout")
@XmlAccessorType(XmlAccessType.FIELD)
@JsonTypeName(value="testLayout")
public class TestLayout extends BaseLayout {
}
```
```
    @Test
    public void test() throws Exception {
        final TestLayout layout = new TestLayout();
        layout.addRecordFilter(new EmptyRecordFilter(Expression.simpleFieldExpression("id")));

        final ObjectMapper mapper = new ObjectMapper();

        // uncomment the line below to see the problem
        // mapper.registerModule(new Hibernate4Module());

        final StringWriter writer = new StringWriter();
        try {
            mapper.writerWithDefaultPrettyPrinter().writeValue(writer, layout);
        } catch (IOException e) {
            fail(e.getMessage());
        }
        final String text = writer.toString();
        System.out.println(text);

        final TestLayout restoredLayout =
            mapper.reader(TestLayout.class).readValue(text);

    }
```
Without *Hibernate4Module* the serialized value looks like this:
```
{
  "recordFilters" : {
    "filters" : [ {
      "@type" : "emptyRecordFilter"
    } ]
  }
}
```
but with the *Hibernate4Module* it is:
```
{
  "recordFilters" : {
    "filters" : [ { } ]
  }
}
```
Excerpt from pom.xml: (note I have tried with using the same version 2.6.1 for all of them and the issues is still here)
```
 <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.4.3</version>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.6.0</version>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-hibernate4</artifactId>
      <version>2.6.1</version>
    </dependency>
```

**Comment by cowtowncoder** [comment] 2016-01-02 17:40
@agorina Thank you -- I'll have a look; should be enough. I will use consistent version for all components for testing.

**Comment by cowtowncoder** [comment] 2016-01-03 23:55
Ok, yes, I can reproduce the issue.

**Comment by cowtowncoder** [comment] 2016-01-04 01:06
Looks like type handler was not being passed properly; needed rather sizable changes so can only be done for 2.7. Will be included in 2.7.0 when it is released soon.

**Closed** 2016-01-04 01:05 UTC

**Comment by agorina** [comment] 2016-01-04 01:12
Thank you! Could you please let me know the estimated timeline for 2.7.0 release?

**Comment by cowtowncoder** [comment] 2016-01-04 02:19
Within 2 weeks, mid-january or earlier.

**Comment by agorina** [comment] 2016-01-04 02:50
Thank you for a prompt response.
