### ISSUE TITLE
Add support for Hibernate 5.2

### ISSUE THREAD

**Issue by mohsenkashi** [FasterXML/jackson-datatype-hibernate#92] opened 2016-06-11 07:06 UTC
Due huge changes in Hibernate 5.2 it is necessary to upgrade version to 5.2

**Comment by mohsenkashi** [comment] 2016-06-11 07:06
I fix it in pull #66

**Comment by cowtowncoder** [comment] 2016-06-11 22:20
Could you please elaborate what you mean by "have to upgrade"? I am fine fixing issues that would exist when used with 5.2, but ideally version we mandate should be an early 5.x minor version for maximal compatibility -- users are unlikely to base their choice of Hibernate version based on what jackson module would like.

So we should not require specific later 5.x minor version if at all possible to avoid (yes, currently 5.1 is required which seems unfortunate).
Module should of course also work with 5.2, I just would not want to break backwards compatibility with 5.1 if that is the cost.

**Comment by ptahchiev** [comment] 2016-08-11 07:57
Hello for me `jackson-datatype-hibernate5` does not work with hibernate 5.2. I have a `spring-data-rest` project that exposes hibernate lazy loaded proxies via rest and it all works fine with hibernate 5.0.x and hibernate 5.1.x but when I try to upgrade to hibernate 5.2 with `jackson-datatype-hibernate5` I get this error: `Id must be assignable to Serializable! Object of class [null] must be an instance of interface java.io.Serializable`. It is well documented here:

http://stackoverflow.com/questions/26322985/id-must-be-assignable-to-serializable-with-lazy-manytoone

https://jira.spring.io/browse/DATAJPA-630

https://jira.spring.io/browse/DATAREST-359

This error was appearing before with hibernate 5.1 and then I followed the recommendation on stackoverflow to add `jackson-datatype-hibernate5` to the classpath and it stopped appearing. Several months later I upgraded to hibernate 5.2 and it starts appearing again.

**Comment by cowtowncoder** [comment] 2016-08-23 05:21
@ptahchiev At this point module can not work with HIbernate 5.2 since module is using part of non-public API that was included in 5.0 and 5.1 but removed from 5.2. There was an attempt (#66) to resolve this, but that unfortunately would not work with 5.0 and 5.1, so we are still missing a solution that would work for these existing hibernate 5.x versions.

I am not sure the exception you get is the primary cause; rather it seems likely that it would be a secondary exception triggered by actual failure during class loading.

**Comment by coladict** [comment] 2016-10-31 14:12
Hi, you're saying it doesn't work with Hibernate 5.2, but my project is using Hibernate 5.2.2.Final and Jackson version 2.7.5 with the same version for this module and a lazy object that gets serialized properly. Could this be a regression bug for the ones experiencing it?

I don't know if it would also get deserialized properly if I didn't have a custom deserializer, which fetches it the existing object from the database, because it is only being sent to the server as an id.

**Comment by Ramblurr** [comment] 2016-11-15 12:27
I'm experiencing the exact same issue as @ptahchiev  (down to the exception, + usage of spring-data-rest). Are there any updates regarding this?

**Comment by mshima** [comment] 2016-11-23 20:08
Added a PR https://github.com/FasterXML/jackson-datatype-hibernate/pull/100
Fixed using reflection, the alternative seems to create another module for hibernate 5.2

**Comment by cowtowncoder** [comment] 2016-12-06 02:41
Fix #100 merged; thank you @mohsenkashi and @mshima!

**Closed by cowtowncoder** 2016-12-06 02:41 UTC
